credentials:
  usernames:
    user1:
      email: user1@example.com
      name: User One
      password: "$2b$12$FsdIzrVLdeV/fBl.Eoer0eg9S2yqWfyVTYeOv4S.iPR8eCo.rhDOS"
    user2:
      email: user2@example.com
      name: User Two
      password: "$2b$12$EGupuiEEf/T9wp73hKfYEOgv5SrcPQzXxqkLpDbGHoM6iur3FqyI2"

cookie:
  expiry_days: 30
  key: some_random_key
  name: some_cookie_name

preauthorized:
  emails:
    - preauthorized@example.com
